version: "3.8"

services:
    fountain-pen:
        image: fountain-pen:latest
        build:
            context: .
            target: production
        ports:
            - "3000:3000"
        volumes:
            - .env.local:/app/.env.local
            # Data folder
            - ./data:/app/data:rw
        environment:
            NODE_ENV: production
